# Generated by Django 3.2.20 on 2023-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgscan', '0003_auto_20230812_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='networkName',
            field=models.CharField(default='not provided', max_length=200),
            preserve_default=False,
        ),
    ]
